import type { NextPage } from 'next'
import { useState, FormEvent } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
const [number, setNumber] = useState("");
const [message, setMessage] = useState("");

function handleSubmit(event: FormEvent) {
  event.preventDefault();

  window.open(`https://api.whatsapp.com/send?phone=+55${number}&text=${message}`);

}


  return (
   <div>
      <Head>
        <title>Direct Zap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<section className="wrapper container-fluid text-center" style={{height: "50% !important;", background: "#009688"}}>
  
		<div className="container desktop">
			<div className="col-md-12 container">
        <img src="https://static.whatsapp.net/rsrc.php/ym/r/36B424nhiL4.svg"/>
				<h2 className="h2"> 
				Envie Whats App para qualquer número sem adicionar o contato
				</h2>
			</div>
			
    </div>
  </section>
  
  <form onSubmit={handleSubmit}>
  <section className="wrapper" style={{ backgroundColor: "#e7e7e7;"}}>
        <div className="container">            
           
   
				<div className="col-md-12 form-group">
          <input name="tel"
          type="tel"
          placeholder="Digite o número com o DDD" 
          className="form-control"
          style={{marginBottom:"20px"}}
          onChange={e =>setNumber(e.target.value)}
          />
         
        </div>
                
          <div className="row">
              <div className="col-md-12 col-xs-12 form-group">
              <textarea name="msg" 
                  className="textarea form-control"
                  placeholder="Digite aqui a mensagem que quer enviar para algum Whats App sem 
                  adicionar o contato"
                  onChange={e =>setMessage(e.target.value)}
                  style={{height: "319px;"}}
                />
              </div> 
              <div className="col-md-12  text-center">
              <input name="btn" className="btnSub" type="submit" value="Enviar Mensagem"/>
              </div>
          </div>
	
        </div>
    </section>
    
    
  </form>
  
  
  
    </div>
	
  )
}

export default Home
